# Generated by Django 2.2.6 on 2019-11-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=1)),
                ('phone', models.CharField(db_index=True, max_length=11)),
                ('label', models.CharField(blank=True, choices=[('V', 'VIP-клиент'), ('K', 'Конфликтный'), ('D', 'Должник')], max_length=1)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('articul', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('A', 'Не закуплен'), ('B', 'Ожидается'), ('C', 'В наличии'), ('D', 'Выдан'), ('E', 'Возврат')], default='A', max_length=1)),
                ('price_purchase', models.IntegerField(max_length=10)),
                ('price_sale', models.IntegerField(max_length=10)),
                ('info_car', models.CharField(max_length=80)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('A', 'В работе'), ('B', 'Завершен')], default='A', max_length=1)),
                ('deposit', models.IntegerField(default='0', max_length=10)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Client')),
                ('product', models.ManyToManyField(related_name='order', to='orders.Product')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makes', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('vin', models.CharField(max_length=25)),
                ('hp', models.FloatField(blank=True, max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='orders.Client')),
            ],
        ),
    ]
