# Generated by Django 2.2.6 on 2019-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='body',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
