# Generated by Django 2.2.6 on 2019-11-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='slug',
        ),
    ]
