# Generated by Django 2.2.6 on 2019-10-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191014_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cars', to='orders.Client'),
        ),
    ]
