# Generated by Django 2.2.6 on 2019-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191119_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fath_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
