# Generated by Django 2.2.6 on 2019-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_client_fath_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hp',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
