# Generated by Django 2.2.6 on 2019-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191120_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_purchase',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sale',
            field=models.FloatField(max_length=20),
        ),
    ]
