# Generated by Django 2.2.6 on 2019-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191120_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='debt',
            field=models.FloatField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='summa',
            field=models.FloatField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit',
            field=models.FloatField(default='0', max_length=20),
        ),
    ]
