# Generated by Django 2.2.6 on 2019-12-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191125_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Contractor'),
        ),
    ]
